### ISSUE TITLE
Simplify the path usage for methods

### ISSUE THREAD

**Issue by adrienluitot** [s0lst1ce/PyGUI#9]
For methods like to create an image button or a background, make that the path is like that "demo/png/buton/blablabla.png" and do the `os.path.join()` in the method.
To have something like : 
`HighlightedLabel.from_background("demo/png/button/blank/extbg2.png", text="BOOM!", offset=(25, 0))`
instead of: 
`HighlightedLabel.from_background(os.path.join("demo", "png", "button", "blank", "textbg2.png"), text="BOOM!", offset=(25, 0))`

**Comment by s0lst1ce** [comment]
There are currently multiple supported formats. The first that you mentioned is a tuple of strings. The second is a plain string, which is what you just asked.
However I recommend that if you provide the full path you do so using `os.path.join()` for it will make a string fitting the current OS.
